mabrains/globalfoundries-pdk-libs-gf180mcu_fd_pr

.github/workflows/drc_gf180mcu_fd_io_test.yml
.github/workflows/drc_gf180mcu_fd_ip_sram_test.yml
.github/workflows/drc_gf180mcu_fd_sc_mcu7t5v0_test.yml
.github/workflows/drc_gf180mcu_fd_sc_mcu9t5v0_test.yml
.github/workflows/drc_regression_test.yml
.github/workflows/drc_switch_checking_test.yml
.github/workflows/lvs_gf180mcu_fd_sc_mcu7t5v0_test.yml
.github/workflows/lvs_gf180mcu_fd_sc_mcu9t5v0_test.yml
.github/workflows/lvs_regression.yml
.github/workflows/lvs_switch_checking_test.yml

Fix ci change order

---

rules/klayout/drc/gf180mcu.drc
rules/klayout/lvs/gf180mcu.lvs
rules/klayout/macros/gf180mcu_drc.lydrc
rules/klayout/macros/gf180mcu_lvs.lylvs
rules/klayout/macros/gf180mcu_options.lym

Adding drop down menu for klayout

Adding drop down menu for klayout

---

models/ngspice/testing/regression/resistor_r/models_regression.py

Fixing all resistor issues.

---

cells/klayout/pymacros/cells/draw_mos.py

Fixing MOSFET Pcell Bulk Tie

---

models/ngspice/sm141064.ngspice
models/ngspice/sm141064_mim.ngspice
models/ngspice/smbb000149.ngspice
models/ngspice/testing/regression/mimcap_c/models_regression.py
models/xyce/sm141064.xyce
models/xyce/sm141064_mim.xyce
models/xyce/smbb000149.xyce
models/xyce/testing/regression/mimcap_c/models_regression.py

Updating primitves names for models files

---

rules/klayout/lvs/README.md
rules/klayout/lvs/gf180mcu.lvs

Update readme file and LVS rule deck

 Updating primitves names in lvs rule deck and its README file

---

rules/klayout/drc/testing/run_regression.py
rules/klayout/drc/testing/run_sc_regression.py
rules/klayout/lvs/testing/Makefile
rules/klayout/lvs/testing/run_regression.py
rules/klayout/lvs/testing/run_sc_regression.py

Make sure that CI will fail if there is a failure.

Make sure that we don't mask failures and remove any os.system call.

---

rules/klayout/drc/rule_decks/comp.drc
rules/klayout/drc/rule_decks/contact.drc
rules/klayout/drc/rule_decks/efuse.drc
rules/klayout/drc/rule_decks/metaltop.drc
rules/klayout/drc/rule_decks/via1.drc
rules/klayout/drc/rule_decks/via2.drc
rules/klayout/drc/rule_decks/via3.drc
rules/klayout/drc/rule_decks/via4.drc
rules/klayout/drc/rule_decks/via5.drc

Performance Enhancement for DRC rule deck.

Performance Enhancement for DRC rule deck.

---

rules/klayout/drc/rule_decks/via1.drc
rules/klayout/drc/rule_decks/via2.drc
rules/klayout/drc/rule_decks/via3.drc
rules/klayout/drc/rule_decks/via4.drc
rules/klayout/drc/rule_decks/via5.drc

Updating vias to make them faster.

modifying via1->via5

---

models/ngspice/testing/regression/bjt_beta/model_reg.py
models/ngspice/testing/regression/mimcap_c/model_reg.py

- modifying models_regression coding in a new model_reg file

Modifying models regression

---

rules/klayout/drc/rule_decks/comp.drc
rules/klayout/drc/rule_decks/main.drc

- Enhancing the implementation of some drc rules in comp table

Fixing some rules & optimizing comp drc table

---

rules/klayout/drc/rule_decks/sab.drc

- Updating sab derivations to be more realistic 
-  Optimizing rules and changing some implementations  like SB.15, ..
- Both runs are : deep
- testcase used for both: https://github.com/efabless/caravel-gf180mcu/blob/main/gds/caravel.gds.gz
- Before [~ 12.8 min]
- After [~ 1.5 min]

Fixing and optimizing sab table

---

models/ngspice/testing/regression/diode/device_netlists/cv.spice
models/ngspice/testing/regression/diode/device_netlists/iv.spice
models/ngspice/testing/regression/diode/model_reg.py

regenerate diode model regressions in a new model_reg file

modifying diode model regression

---

rules/klayout/drc/rule_decks/ldnmos.drc

- Fixing 2 rules in mdn table like mdn3a & mdn3b
- Optimizing some rules in mdn table for gf180 mcu [Till mdn4 rule]

Optimizing some rules in mdn table till mdn4

---

models/ngspice/testing/regression/bjt_beta/device_netlists/npn.spice
models/ngspice/testing/regression/bjt_beta/device_netlists/pnp.spice
models/ngspice/testing/regression/bjt_beta/model_reg.py

regenerate bjt_beta models regression file in a new model_reg file

regenerating bjt_beta models regression

---

models/ngspice/testing/regression/bjt_iv/device_netlists/npn.spice
models/ngspice/testing/regression/bjt_iv/device_netlists/pnp.spice
models/ngspice/testing/regression/bjt_iv/model_reg.py

Last version for Bjt_iv_regression.
Results of regression:

Bjt_iv regression 

---

models/ngspice/testing/regression/bjt_cj/device_netlists/npn_CBJ.spice
models/ngspice/testing/regression/bjt_cj/device_netlists/npn_CSJ.spice
models/ngspice/testing/regression/bjt_cj/device_netlists/npn_EBJ.spice
models/ngspice/testing/regression/bjt_cj/device_netlists/pnp_CBJ.spice
models/ngspice/testing/regression/bjt_cj/device_netlists/pnp_EBJ.spice
models/ngspice/testing/regression/bjt_cj/models_regression.py

fix some issues in funcs (ext_measured,run_sim)
complete func run_sims
create func error_calc
edit the spice file template
there was problem for npn devices for CSJ cap so
Calc. is ignored for CSJ junction as simulator behaves in a different way
[it gives nan. results for high temp for all voltage values and it gives constant cap. at different voltages for low temp]
check availability of running the code from the make file

complete the code and fix it is issues

---

models/ngspice/testing/regression/bjt_beta/plotting.ipynb
models/ngspice/testing/regression/bjt_cj/plotting.ipynb
models/ngspice/testing/regression/bjt_iv/plotting.ipynb
models/ngspice/testing/regression/diode/plotting.ipynb
models/ngspice/testing/regression/mimcap_c/plotting.ipynb
models/ngspice/testing/regression/moscap_c/plotting.ipynb
models/ngspice/testing/regression/resistor_r/plotting.ipynb

add notebooks to plot the measurements against the simulation
the notebooks calls the models_regressions so it depend on pull [request](https://github.com/mabrains/globalfoundries-pdk-libs-gf180mcu_fd_pr/pull/53)

add notebooks to plot the measurements against the simulation

---

rules/klayout/drc/rule_decks/ldnmos.drc

- Optimizing some rules in ldnmos DRC table like MDN.5, MDN.6

Fixing and optimizing some rules in LDNMOS table

---

cells/klayout/pymacros/cells/__init__.py
cells/klayout/pymacros/cells/bjt.py
cells/klayout/pymacros/cells/diode.py
cells/klayout/pymacros/cells/draw_bjt.py
cells/klayout/pymacros/cells/draw_diode.py

- Rewriting BJT pcells to fix some issues 
- Renaming some diodes pcells with its new names

Pcells cleanup

---

models/xyce/testing/regression/mos_iv_vgs/device_netlists_Id/nfet_03v3_dss_iv.spice
models/xyce/testing/regression/mos_iv_vgs/device_netlists_Id/nfet_03v3_iv.spice
models/xyce/testing/regression/mos_iv_vgs/device_netlists_Id/nfet_06v0_dss_iv.spice
models/xyce/testing/regression/mos_iv_vgs/device_netlists_Id/nfet_06v0_iv.spice
models/xyce/testing/regression/mos_iv_vgs/device_netlists_Id/nfet_06v0_nvt_iv.spice
models/xyce/testing/regression/mos_iv_vgs/device_netlists_Id/pfet_03v3_dss_iv.spice
models/xyce/testing/regression/mos_iv_vgs/device_netlists_Id/pfet_03v3_iv.spice
models/xyce/testing/regression/mos_iv_vgs/device_netlists_Id/pfet_06v0_dss_iv.spice
models/xyce/testing/regression/mos_iv_vgs/device_netlists_Id/pfet_06v0_iv.spice
models/xyce/testing/regression/mos_iv_vgs/device_netlists_Id/run_nfet_independently.spice
models/xyce/testing/regression/mos_iv_vgs/device_netlists_Rds/nfet_03v3_dss_iv.spice
models/xyce/testing/regression/mos_iv_vgs/device_netlists_Rds/nfet_03v3_iv.spice
models/xyce/testing/regression/mos_iv_vgs/device_netlists_Rds/nfet_06v0_dss_iv.spice
models/xyce/testing/regression/mos_iv_vgs/device_netlists_Rds/nfet_06v0_iv.spice
models/xyce/testing/regression/mos_iv_vgs/device_netlists_Rds/nfet_06v0_nvt_iv.spice
models/xyce/testing/regression/mos_iv_vgs/device_netlists_Rds/pfet_03v3_dss_iv.spice
models/xyce/testing/regression/mos_iv_vgs/device_netlists_Rds/pfet_03v3_iv.spice
models/xyce/testing/regression/mos_iv_vgs/device_netlists_Rds/pfet_06v0_dss_iv.spice
models/xyce/testing/regression/mos_iv_vgs/device_netlists_Rds/pfet_06v0_iv.spice
models/xyce/testing/regression/mos_iv_vgs/device_netlists_Rds/run_nfet_03v3_rds_independently.spice
models/xyce/testing/regression/mos_iv_vgs/models_regression.py

complete mos_iv_vgs with new regression

complete mos_iv_vgs with Xyce new regression

---

rules/klayout/drc/run_drc.py

- Updating klayout version check for run_drc script

Updating klayout version check

---

rules/klayout/drc/testing/Makefile
rules/klayout/drc/testing/run_regression.py

- Starting in DRC regression rewriting using new style

Starting in new DRC regression

---

models/ngspice/testing/regression/bjt_beta/models_regression.py
models/ngspice/testing/regression/bjt_cj/models_regression.py
models/ngspice/testing/regression/bjt_iv/device_netlists/npn.spice
models/ngspice/testing/regression/bjt_iv/device_netlists/pnp.spice
models/ngspice/testing/regression/bjt_iv/models_regression.py
models/ngspice/testing/regression/bjt_iv/plotting.ipynb
models/ngspice/testing/regression/diode/models_regression.py
models/ngspice/testing/regression/mimcap_c/models_regression.py
models/ngspice/testing/regression/mos_cv/models_regression.py
models/ngspice/testing/regression/mos_iv_vbs/models_regression.py
models/ngspice/testing/regression/mos_iv_vgs/models_regression.py
models/ngspice/testing/regression/moscap_c/models_regression.py
models/ngspice/testing/regression/resistor_r/models_regression.py

complete the rest of the devices

Ngspice regression

---

rules/klayout/drc/testing/Makefile
rules/klayout/drc/testing/run_regression.py

Drc regression

---

rules/klayout/drc/testing/run_regression.py

Cleanup regression script

---

cells/klayout/pymacros/cells/__init__.py
cells/klayout/pymacros/cells/draw_fet.py
cells/klayout/pymacros/cells/fet.py
cells/klayout/pymacros/cells/layers_def.py

adding nfet_6v0_nat pcell using gdsfactory

adding nfet_6v0_nat pcell using gdsfactory rather than using klayout base implementation.

---

cells/klayout/pymacros/cells/draw_fet.py
cells/klayout/pymacros/cells/layers_def.py

adding GF180MCU pfet pcell using gdsfactory

adding pfet pcell using gdsfactory rather than using klayout base implementation.

---

cells/klayout/pymacros/cells/layers_def.py
cells/klayout/pymacros/cells/via_generator.py

adding all layers def to layers_def.py  and modifying via_generator import

adding all layers definitions and modifying via_generator import

---

.github/workflows/ngspice.yml
cells/klayout/pymacros/cells/__init__.py
cells/klayout/pymacros/cells/cap_mim.py
cells/klayout/pymacros/cells/draw_cap_mim.py
cells/klayout/pymacros/cells/layers_def.py
cells/klayout/pymacros/cells/via_generator.py

adding mimcap pcells using gdsfactory

adding mimcap pcells using gdsfactory rather than using klayout base implementation. 

---

cells/klayout/pymacros/cells/diode.py
cells/klayout/pymacros/cells/draw_diode.py

adding diode labels for : 
* diode_nd2ps
* diode_pd2nw
* diode_nw2ps
* diode_pw2dw
* diode_dw2ps
* sc_diode

Adding diodes label option

---

cells/klayout/pymacros/cells/cap_mim.py
cells/klayout/pymacros/cells/draw_cap_mim.py
cells/klayout/pymacros/cells/layers_def.py

* adding mimcap labels 
* modify metal3_label layer in layers_def

adding mimcap_label option

---

cells/klayout/pymacros/cells/cap_mos.py
cells/klayout/pymacros/cells/draw_cap_mos.py

Adding moscap labels option

---

cells/klayout/pymacros/cells/draw_res.py
cells/klayout/pymacros/cells/res.py

adding resistor devices labels

Adding res labels option

---

cells/klayout/pymacros/cells/draw_fet.py

fixing issues of fet pcells : 
* type violation issue when some parameters doesn't have default value
* labels layer to be of the hight connected layer 
* gate_label option to follow number of transistor with interdigitation instead of number of fingers

Fixing labels layers modifying some fet pcell issues

---

cells/klayout/pymacros/cells/draw_fet.py

fixing a draw_fet generation issue

fixing a draw_fet generation issue

---

cells/klayout/pymacros/cells/draw_fet.py
cells/klayout/pymacros/cells/fet.py

make interdigitation patterns label optional

adding interdigit patterns label as an option

---

.github/workflows/ngspice.yml
.github/workflows/regression.yml
Makefile
models/ngspice/testing/regression/bjt_beta/models_regression.py
models/ngspice/testing/regression/bjt_cj/models_regression.py
models/ngspice/testing/regression/bjt_iv/models_regression.py
models/ngspice/testing/regression/diode/models_regression.py
models/ngspice/testing/regression/mimcap_c/models_regression.py
models/ngspice/testing/regression/mos_cv/models_regression.py
models/ngspice/testing/regression/mos_iv_vbs/models_regression.py
models/ngspice/testing/regression/mos_iv_vgs/models_regression.py
models/ngspice/testing/regression/moscap_c/models_regression.py
models/ngspice/testing/regression/resistor_r/models_regression.py

- Adding git actions for models-ngspice
-  Modifying all regression scripts to fail on large differences 
- Cleaning flake issues like C901

Adding actions for models-ngspice and cleaning flake issues

---

rules/klayout/drc/rule_decks/metaltop.drc

Fixes https://github.com/efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr/issues/30

Adding support for METALTOP 11k for GF180MCU DRC

---

rules/klayout/lvs/gf180mcu.lvs

Adding LVS update to allow multiple file extension for netlist.

Adding LVS update to allow multiple file extension for netlist.

---

models/xyce/design.xyce
models/xyce/testing/Makefile
models/xyce/testing/regression/bjt_beta/models_regression.py
models/xyce/testing/regression/bjt_cj/models_regression.py
models/xyce/testing/regression/bjt_iv/models_regression.py
models/xyce/testing/regression/diode/models_regression.py
models/xyce/testing/regression/mimcap_c/models_regression.py
models/xyce/testing/regression/mos_cv/models_regression.py
models/xyce/testing/regression/mos_iv_vbs/models_regression.py
models/xyce/testing/regression/mos_iv_vgs/models_regression.py
models/xyce/testing/regression/moscap_c/models_regression.py
models/xyce/testing/regression/resistor_r/models_regression.py
models/xyce/testing/sc_regression/gf180mcu_fd_sc_mcu7t5v0/models_regression.py
models/xyce/testing/smoke_test/xyce_smoke_test.py

Cleaning and fixing some issues in xyce regression for GF180MCU

---

cells/klayout/pymacros/testing/drc_test/Makefile

Updating Pcells testing to use PV repo for GF180MCU

---

cells/klayout/pymacros/cells/via_generator.py

fixing issue related to metal levels

fixing metal_level issue

---

cells/klayout/pymacros/cells/via_generator.py
cells/klayout/pymacros/cells/vias_gen.py

fixing start and end layer issue

fixing start amd end layers issue

---

cells/klayout/pymacros/cells/via_generator.py
cells/klayout/pymacros/cells/vias_gen.py

fixing start and end layers naming

fixing start amd end layers names

---

models/ngspice/sm141064.ngspice
models/xyce/sm141064.xyce

Adding support for m parm for FETs in GF180 models

---

cells/klayout/pymacros/cells/cap_mim.py
cells/klayout/pymacros/testing/cdl_gen.py
cells/klayout/pymacros/testing/patterns/mim_caps/mim_cap_optionA_patterns.csv
cells/klayout/pymacros/testing/patterns/mim_caps/mim_cap_optionB_4LM_patterns.csv
cells/klayout/pymacros/testing/patterns/mim_caps/mim_cap_optionB_5LM_patterns.csv
cells/klayout/pymacros/testing/patterns/mim_caps/mim_cap_optionB_6LM_patterns.csv

mim_caps lvs testing and modifying parameters

---

cells/klayout/pymacros/cells/cap_mos.py
cells/klayout/pymacros/cells/draw_cap_mos.py
cells/klayout/pymacros/testing/patterns/mos_caps/cap_nmos_b_patterns.csv
cells/klayout/pymacros/testing/patterns/mos_caps/cap_nmos_patterns.csv
cells/klayout/pymacros/testing/patterns/mos_caps/cap_pmos_b_patterns.csv
cells/klayout/pymacros/testing/patterns/mos_caps/cap_pmos_patterns.csv

mos_cap pcells lvs testing

---

cells/klayout/pymacros/README.md
cells/klayout/pymacros/cells/cap_mim.py
cells/klayout/pymacros/cells/draw_cap_mos.py
cells/klayout/pymacros/cells/draw_diode.py
cells/klayout/pymacros/cells/draw_fet.py
cells/klayout/pymacros/cells/draw_res.py
cells/klayout/pymacros/cells/via_generator.py
cells/klayout/pymacros/testing/Makefile
cells/klayout/pymacros/testing/README.md

renaming gdsfactory_types module and modify readme files

---

rules/klayout/macros/drc_options.yml
rules/klayout/macros/gf180mcu_drc.lydrc
rules/klayout/macros/gf180mcu_lvs.lylvs
rules/klayout/macros/gf180mcu_options.lym
rules/klayout/macros/lvs_options.yml

updating klayout dropdown menues

---

rules/klayout/macros/gf180mcu_drc.lydrc
rules/klayout/macros/run_drc_main/main.drc

storing a dummy main.drc and renaming database file

---

models/ngspice/sm141064.ngspice
models/ngspice/sm141064_mim.ngspice

Modify the MIM cap models

---

models/ngspice/smbb000149.ngspice

editing the 10v transistor caps

editing the 10v transistor caps

---

cells/klayout/pymacros/cells/draw_fet.py

fixing contact-pcomp enclosure drc issue at minimum width pfet cell

fixing drc issue for minimum width pfet cell

---

.gitignore
cells/klayout/pymacros/cells/draw_cap_mim.py
cells/klayout/pymacros/cells/draw_cap_mos.py
cells/klayout/pymacros/cells/draw_diode.py
cells/klayout/pymacros/cells/draw_fet.py
cells/klayout/pymacros/cells/draw_res.py
cells/klayout/pymacros/cells/fet.py
cells/klayout/pymacros/cells/via_generator.py
cells/klayout/pymacros/cells/vias_gen.py
cells/klayout/pymacros/testing/Makefile

Fixing some issues in pcells with latest gf version

---

models/ngspice/sm141064.ngspice
models/xyce/sm141064.xyce

Fixing #https://github.com/efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr/issues/40

Updating GF180MCU models for mismatch analysis

---

rules/klayout/macros/gf180mcu_drc.lydrc
rules/klayout/macros/gf180mcu_options.lym
rules/klayout/macros/run_drc_main/layers_def.drc

In this PR, we will make the following changes: 
* update variant stack in klayout drc menu to match pv 
* add layers_def file to main_drc_run directory

Fix klayout menues

---

cells/klayout/pymacros/cells/draw_fet.py

update pfet_dn pcells

---

cells/klayout/pymacros/cells/draw_fet.py

In this PR the following changes are done : 
* fix enclosure statement in draw_fet script 
* fix list index type read in draw_fet script

fix typos in draw_fet script
